apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: renaissancec
  labels:
    team: renaissancec-frontend
spec:
  selector:
    matchLabels:
        app: renaissancec-app
  endpoints:
    - port: renaissancec-port
      path: '/metrics'
